name:                ATPPFHS
version:             0.1.0.0
github:              "https://github.com/SnowOnion/ATPPFHS"
license:             MIT
author:              "SOnion"
maintainer:          "at snowonionlee $ dot gmail com"
copyright:           "2018 SOnion"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SnowOnion/ATPPFHS.hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec

library:
  source-dirs: src

executables:
  ATPPFHS-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ATPPFHS

tests:
  ATPPFHS-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ATPPFHS
